DROP TABLE IF EXISTS cookbooks CASCADE;
DROP TABLE IF EXISTS recipes;

CREATE TABLE cookbooks (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  type TEXT NOT NULL
);

CREATE TABLE recipes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  cookbook_id BIGINT REFERENCES cookbooks(id)
)